#! /bin/sh

# visuals
bspc config border_width        2
bspc config window_gap          8
bspc config split_ratio         0.55
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focused_border_color "#FF85AD"
bspc config active_border_color "#999999"
bspc config presel_feedback_color "#3399FF"
bspc config click_to_focus button1
#bspc config external_rules_command ~/.config/bspwm/external_rules


#Left Monitor
#bspc monitor DVI-D-0 -d M1A M1B

#Right Monitor
bspc monitor HDMI-0 -d M2A M2B M2C

#Small Monitor
bspc monitor DVI-I-0 -d M3A M3B

#bspc wm --reorder-monitors DVI-D-0 HDMI-0 DVI-I-0
bspc wm --reorder-monitors HDMI-0 DVI-I-0


# application rules
bspc rule -a firefox private=on
bspc rule -a mpv private=on
bspc rule -a qemu-system-i386 state=floating
bspc rule -a VirtualBoxVM state=floating


# launch applications

~/scripts/startup_applications
